//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevHelp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomMessages
    {
        public System.Guid Id { get; set; }
        public System.Guid Room_Id { get; set; }
        public System.Guid Message_Id { get; set; }
    
        public virtual Messages Messages { get; set; }
        public virtual Rooms Rooms { get; set; }
    }
}
